from fleet_acceleration import fleet_acceleration
from fleet_build_repair_parametr import fleet_build_repair_parametr
from fleet_energy_power import fleet_energy_power
from fleet_engine_parametr import fleet_engine_parametr
from fleet_parametr_resource_extraction import fleet_parametr_resource_extraction
from fleet_scan_parametr import fleet_scan_parametr
from ship_module_hold import ship_module_hold
from fleet_parametr import fleet_parametr

