# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_game', '0007_auto_20160101_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armorpattern',
            name='armor_health',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='armorpattern',
            name='armor_mass',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='armorpattern',
            name='armor_power',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='armorpattern',
            name='armor_regeneration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='armorpattern',
            name='value_energy_resistance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='armorpattern',
            name='value_phisical_resistance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='enginepattern',
            name='engine_health',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='enginepattern',
            name='engine_mass',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='enginepattern',
            name='engine_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='enginepattern',
            name='giper_power',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='enginepattern',
            name='intersystem_power',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='enginepattern',
            name='nullT_power',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='enginepattern',
            name='power_consuption',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='enginepattern',
            name='system_power',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='generatorpattern',
            name='fuel_necessary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='generatorpattern',
            name='generator_health',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='generatorpattern',
            name='generator_mass',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='generatorpattern',
            name='generator_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='generatorpattern',
            name='produced_energy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shellpattern',
            name='shell_mass',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shellpattern',
            name='shell_phisical_damage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shellpattern',
            name='shell_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shellpattern',
            name='shell_speed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shieldpattern',
            name='number_of_emitter',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shieldpattern',
            name='power_consuption',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shieldpattern',
            name='shield_health',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shieldpattern',
            name='shield_mass',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shieldpattern',
            name='shield_regeneration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shieldpattern',
            name='shield_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shieldpattern',
            name='value_energy_resistance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shieldpattern',
            name='value_phisical_resistance',
            field=models.IntegerField(),
        ),
    ]
